server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true

mybatis:
  config-location: classpath:mybatis/mapper-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml


spring:
  datasource:
    driver-class-name: ${DB_CLASS}
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000
      max-lifetime: 60000
      connection-timeout: 30000
  #    url:
  #    username:
  #    password:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

  profiles:
    active: secret

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: DEBUG


