name: CI/CD Pipeline for Backend

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    # gradlew 파일에 실행 권한 추가
    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    # Build backend, continue on test failure
    - name: Build backend
      run: CI='' ./gradlew build || true  # 테스트 실패 시에도 성공으로 간주

    # Deploy to EC2
    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
      run: |
        echo "${SSH_PRIVATE_KEY}" > private_key.pem
        chmod 600 private_key.pem
        # Add EC2 host to known_hosts to bypass host verification
        mkdir -p ~/.ssh
        ssh-keyscan -H "${EC2_HOST}" >> ~/.ssh/known_hosts
        scp -i private_key.pem -o StrictHostKeyChecking=no build/libs/*.jar ec2-user@${EC2_HOST}:/home/ec2-user/backEnd-dev/
        ssh -i private_key.pem -o StrictHostKeyChecking=no ec2-user@${EC2_HOST} "nohup java -jar /home/ec2-user/backEnd-dev/*.jar --server.port=8080 &"
